import type {
  Signal,
  Strategy,
  TradeEntry,
  DashboardStats,
  HeatmapCell,
  InstitutionalFlowData,
  BrokerConfig,
  MarketSentiment,
  SectorStrength,
  SmartMoneyActivity,
  VolatilityData,
  EquityPoint,
  MonthlyReturn,
  BacktestResult,
  StrategyPerformance,
  TelegramConfig,
  UserSettings,
  MarketBreadth,
} from "./types";
import { historicalTrades } from "./trade-history";

// ============================================================
// Dashboard
// ============================================================

export const dashboardStats: DashboardStats = {
  aiEngineStatus: "active",
  marketStatus: "open",
  capital: 2500000,
  todayPnl: 47350,
  todayPnlPercent: 1.89,
  activeStrategies: 5,
  winRate: 73.2,
  totalTrades: 1847,
  totalProfit: 1247500,
};

export const marketBreadth: MarketBreadth = {
  advancing: 1287,
  declining: 842,
  unchanged: 156,
};

export const heatmapData: HeatmapCell[] = [
  { symbol: "RELIANCE", sector: "Energy", change: 2.3, volume: 15400000 },
  { symbol: "TCS", sector: "IT", change: -1.1, volume: 8200000 },
  { symbol: "HDFCBANK", sector: "Banking", change: 1.7, volume: 12300000 },
  { symbol: "INFY", sector: "IT", change: -0.4, volume: 9100000 },
  { symbol: "ICICIBANK", sector: "Banking", change: 0.9, volume: 11800000 },
  { symbol: "HINDUNILVR", sector: "FMCG", change: -0.7, volume: 4500000 },
  { symbol: "ITC", sector: "FMCG", change: 1.2, volume: 18900000 },
  { symbol: "SBIN", sector: "Banking", change: 3.1, volume: 22100000 },
  { symbol: "BHARTIARTL", sector: "Telecom", change: 0.5, volume: 7800000 },
  { symbol: "KOTAKBANK", sector: "Banking", change: -0.3, volume: 5600000 },
  { symbol: "LT", sector: "Capital Goods", change: 1.8, volume: 6700000 },
  { symbol: "AXISBANK", sector: "Banking", change: 2.1, volume: 14200000 },
  { symbol: "ASIANPAINT", sector: "Consumer", change: -1.9, volume: 3200000 },
  { symbol: "MARUTI", sector: "Auto", change: 0.8, volume: 4100000 },
  { symbol: "TITAN", sector: "Consumer", change: 1.5, volume: 5900000 },
  { symbol: "SUNPHARMA", sector: "Pharma", change: -0.6, volume: 8400000 },
  { symbol: "BAJFINANCE", sector: "Finance", change: 2.7, volume: 10500000 },
  { symbol: "WIPRO", sector: "IT", change: -1.3, volume: 7200000 },
  { symbol: "TATAMOTORS", sector: "Auto", change: 3.4, volume: 25600000 },
  { symbol: "ULTRACEMCO", sector: "Cement", change: 0.2, volume: 2800000 },
  { symbol: "POWERGRID", sector: "Power", change: 1.1, volume: 9700000 },
  { symbol: "NTPC", sector: "Power", change: 0.7, volume: 13400000 },
  { symbol: "NESTLEIND", sector: "FMCG", change: -0.5, volume: 1900000 },
  { symbol: "TECHM", sector: "IT", change: -2.1, volume: 6100000 },
];

export const institutionalFlowData: InstitutionalFlowData[] = [
  { date: "Mon", fiiNet: 1250, diiNet: -820 },
  { date: "Tue", fiiNet: -980, diiNet: 1100 },
  { date: "Wed", fiiNet: 2100, diiNet: -450 },
  { date: "Thu", fiiNet: -340, diiNet: 780 },
  { date: "Fri", fiiNet: 1800, diiNet: -1200 },
  { date: "Today", fiiNet: 2450, diiNet: 890 },
];

// ============================================================
// AI Signals
// ============================================================

export const signals: Signal[] = [
  {
    id: "sig-001",
    symbol: "NIFTY 50",
    direction: "BUY",
    confidenceScore: 92,
    probability: 87,
    entry: 23380.00,
    stopLoss: 23340.00,
    target: 23580.00,
    expectedRR: 5.0,
    signalStrength: "Strong",
    generatedTime: new Date(Date.now() - 300000).toISOString(),
    reasoning: [
      "Bullish Order Block (OB) mitigation on 15m TF",
      "Fair Value Gap (FVG) inefficiency filled at 23360",
      "Sell-Side Liquidity (SSL) swept below Asia session low",
      "Market Structure Shift (MSS) with displacement on 5m",
      "Institutional order flow aligned with daily bullish bias",
    ],
    qualityScore: 94,
    status: "active",
    timeframe: "15min",
    optionTradeSetup: {
      contract: "NIFTY 23400 CE",
      premiumEntry: 145.50,
      premiumSL: 115.00,
      premiumTarget: 250.00,
      impliedVolatility: 13.2,
      delta: 0.54,
    }
  },
  {
    id: "sig-002",
    symbol: "BANKNIFTY",
    direction: "SELL",
    confidenceScore: 88,
    probability: 82,
    entry: 50300.00,
    stopLoss: 50360.00,
    target: 49500.00,
    expectedRR: 13.3,
    signalStrength: "Strong",
    generatedTime: new Date(Date.now() - 900000).toISOString(),
    reasoning: [
      "Buy-Side Liquidity (BSL) swept above daily swing high",
      "15m Bearish Order Block mitigation with rejection candle",
      "Fair Value Gap (FVG) formed during Market Structure Shift",
      "Premium pricing area reached on Fibonacci retracement (0.786)",
      "High volume distribution indicating institutional unloading",
    ],
    qualityScore: 91,
    status: "active",
    timeframe: "5min",
    optionTradeSetup: {
      contract: "BANKNIFTY 50300 PE",
      premiumEntry: 240.20,
      premiumSL: 190.00,
      premiumTarget: 410.00,
      impliedVolatility: 15.8,
      delta: -0.52,
    }
  },
  {
    id: "sig-sensex",
    symbol: "SENSEX",
    direction: "BUY",
    confidenceScore: 95,
    probability: 91,
    entry: 74520.00,
    stopLoss: 74400.00,
    target: 75100.00,
    expectedRR: 4.83,
    signalStrength: "Strong",
    generatedTime: new Date(Date.now() - 600000).toISOString(),
    reasoning: [
      "Bollinger Bands (20,2) volatility squeeze breakout on 15m TF",
      "Supertrend (10,3) buy signal triggered on high displacement close",
      "Auto Key Levels mapped weekly horizontal support at 74,500",
      "RSI indicator crossed above 50 midline indicating bullish strength",
      "Volume expansion confirming institutional breakout absorption",
    ],
    qualityScore: 96,
    status: "active",
    timeframe: "15min",
    optionTradeSetup: {
      contract: "SENSEX 74200 CE",
      premiumEntry: 310.50,
      premiumSL: 240.00,
      premiumTarget: 650.00,
      impliedVolatility: 14.8,
      delta: 0.58,
    }
  },
  {
    id: "sig-003",
    symbol: "RELIANCE",
    direction: "BUY",
    confidenceScore: 81,
    probability: 74,
    entry: 2942.35,
    stopLoss: 2932.00,
    target: 2998.00,
    expectedRR: 4.08,
    signalStrength: "Moderate",
    generatedTime: new Date(Date.now() - 1800000).toISOString(),
    reasoning: [
      "Mitigated 1hr bullish breaker block zone",
      "Liquidity pool sweep at key swing support (2935)",
      "Discount pricing area confirmation (0.618 Fib sweep)",
      "Sector rotational strength showing institutional buying",
    ],
    qualityScore: 81,
    status: "active",
    timeframe: "15min",
    optionTradeSetup: {
      contract: "RELIANCE 2940 CE",
      premiumEntry: 48.60,
      premiumSL: 39.00,
      premiumTarget: 78.00,
      impliedVolatility: 17.5,
      delta: 0.51,
    }
  },
  {
    id: "sig-004",
    symbol: "TATAMOTORS",
    direction: "BUY",
    confidenceScore: 89,
    probability: 84,
    entry: 978.40,
    stopLoss: 968.00,
    target: 1015.00,
    expectedRR: 4.28,
    signalStrength: "Strong",
    generatedTime: new Date(Date.now() - 2400000).toISOString(),
    reasoning: [
      "Bullish Order Block mitigation on 5m with displacement",
      "Asia session high sweep followed by market structure shift",
      "Mitigated the 5m Fair Value Gap zone perfectly",
      "Strong FII block deal buying detected at 974 level",
    ],
    qualityScore: 91,
    status: "triggered",
    timeframe: "5min",
    optionTradeSetup: {
      contract: "TATAMOTORS 980 CE",
      premiumEntry: 22.40,
      premiumSL: 17.00,
      premiumTarget: 38.00,
      impliedVolatility: 22.1,
      delta: 0.53,
    }
  },
  {
    id: "sig-005",
    symbol: "HDFCBANK",
    direction: "SELL",
    confidenceScore: 78,
    probability: 69,
    entry: 1628.00,
    stopLoss: 1636.00,
    target: 1595.00,
    expectedRR: 4.12,
    signalStrength: "Moderate",
    generatedTime: new Date(Date.now() - 3600000).toISOString(),
    reasoning: [
      "Bearish Breaker Block formed on 15m timeframe",
      "SSL sweep below 1620 followed by structural failure",
      "Hedge flow distribution sweep at 1635 psychological level",
    ],
    qualityScore: 78,
    status: "active",
    timeframe: "15min",
    optionTradeSetup: {
      contract: "HDFCBANK 1620 PE",
      premiumEntry: 28.40,
      premiumSL: 21.00,
      premiumTarget: 52.00,
      impliedVolatility: 16.4,
      delta: -0.47,
    }
  },
  {
    id: "sig-006",
    symbol: "INFY",
    direction: "BUY",
    confidenceScore: 84,
    probability: 78,
    entry: 1465.00,
    stopLoss: 1452.00,
    target: 1517.00,
    expectedRR: 4.0,
    signalStrength: "Moderate",
    generatedTime: new Date(Date.now() - 4500000).toISOString(),
    reasoning: [
      "Imbalance fill in the 30m Fair Value Gap (FVG)",
      "Daily demand zone bounce with swing low sweep",
      "IT sector index showing structural shift on hourly charts",
    ],
    qualityScore: 85,
    status: "active",
    timeframe: "30min",
    optionTradeSetup: {
      contract: "INFY 1460 CE",
      premiumEntry: 34.20,
      premiumSL: 27.50,
      premiumTarget: 58.00,
      impliedVolatility: 18.2,
      delta: 0.52,
    }
  },
  {
    id: "sig-007",
    symbol: "SBIN",
    direction: "BUY",
    confidenceScore: 96,
    probability: 92,
    entry: 842.15,
    stopLoss: 835.00,
    target: 877.00,
    expectedRR: 5.0,
    signalStrength: "Strong",
    generatedTime: new Date(Date.now() - 600000).toISOString(),
    reasoning: [
      "Institutional order block demand zone held on multiple frames",
      "Bullish breaker block mitigation on 15m",
      "Liquidity swept clean below local swing lows",
      "Relative strength index divergence indicating accumulation",
    ],
    qualityScore: 97,
    status: "active",
    timeframe: "15min",
    optionTradeSetup: {
      contract: "SBIN 840 CE",
      premiumEntry: 18.50,
      premiumSL: 14.00,
      premiumTarget: 34.00,
      impliedVolatility: 19.1,
      delta: 0.55,
    }
  },
  {
    id: "sig-008",
    symbol: "BAJFINANCE",
    direction: "SELL",
    confidenceScore: 73,
    probability: 67,
    entry: 6890.00,
    stopLoss: 6925.00,
    target: 6740.00,
    expectedRR: 4.28,
    signalStrength: "Moderate",
    generatedTime: new Date(Date.now() - 7200000).toISOString(),
    reasoning: [
      "Equal highs swept (BSL sweep) at 6920",
      "1hr Bearish FVG mitigation area",
      "Market structure breakdown confirmed on 15m TF",
    ],
    qualityScore: 71,
    status: "expired",
    timeframe: "1hr",
    optionTradeSetup: {
      contract: "BAJFINANCE 6900 PE",
      premiumEntry: 110.40,
      premiumSL: 80.00,
      premiumTarget: 210.00,
      impliedVolatility: 20.8,
      delta: -0.49,
    }
  },
];

// ============================================================
// Strategies
// ============================================================

export const strategies: Strategy[] = [
  {
    id: "strat-001",
    name: "EMA 9/15 Scalper",
    description: "Fast scalping strategy using 9 and 15 period EMA crossover with volume confirmation. Ideal for index trading in volatile sessions.",
    category: "Scalping",
    winRate: 72.4,
    monthlyReturn: 8.5,
    riskRating: 3,
    maxDrawdown: 4.2,
    sharpeRatio: 2.1,
    totalTrades: 2450,
    isActive: true,
    isPremium: false,
    tags: ["EMA", "Scalping", "Index"],
  },
  {
    id: "strat-002",
    name: "SSMA Trend Rider",
    description: "Medium-term trend following using Smoothed Simple Moving Average. Captures major swings with tight risk management.",
    category: "Trend Following",
    winRate: 65.8,
    monthlyReturn: 12.3,
    riskRating: 2,
    maxDrawdown: 6.1,
    sharpeRatio: 1.8,
    totalTrades: 890,
    isActive: false,
    isPremium: false,
    tags: ["SSMA", "Trend", "Swing"],
  },
  {
    id: "strat-003",
    name: "Opening Range Breakout",
    description: "Captures the first 15-minute range breakout. Works best on indices with high volume opening sessions.",
    category: "Breakout",
    winRate: 68.2,
    monthlyReturn: 9.8,
    riskRating: 4,
    maxDrawdown: 7.3,
    sharpeRatio: 1.6,
    totalTrades: 1820,
    isActive: true,
    isPremium: false,
    tags: ["ORB", "Breakout", "Intraday"],
  },
  {
    id: "strat-004",
    name: "Momentum Hunter",
    description: "Identifies stocks with strong momentum using RSI, MACD, and volume expansion. Targets high-probability momentum moves.",
    category: "Momentum",
    winRate: 71.1,
    monthlyReturn: 11.2,
    riskRating: 3,
    maxDrawdown: 5.5,
    sharpeRatio: 2.3,
    totalTrades: 1560,
    isActive: false,
    isPremium: true,
    tags: ["Momentum", "RSI", "MACD"],
  },
  {
    id: "strat-005",
    name: "Volume Expansion",
    description: "Detects unusual volume spikes and trades in the direction of institutional activity. High accuracy on liquid stocks.",
    category: "Volume",
    winRate: 74.6,
    monthlyReturn: 7.4,
    riskRating: 2,
    maxDrawdown: 3.8,
    sharpeRatio: 2.5,
    totalTrades: 980,
    isActive: true,
    isPremium: true,
    tags: ["Volume", "Institutional", "Accuracy"],
  },
  {
    id: "strat-006",
    name: "Smart Money Concept",
    description: "Order block and liquidity sweep strategy based on smart money concepts. Identifies institutional order flow patterns.",
    category: "Smart Money",
    winRate: 76.3,
    monthlyReturn: 14.1,
    riskRating: 4,
    maxDrawdown: 8.2,
    sharpeRatio: 1.9,
    totalTrades: 720,
    isActive: false,
    isPremium: true,
    tags: ["SMC", "Order Block", "Liquidity"],
  },
  {
    id: "strat-007",
    name: "VWAP Reversal",
    description: "Mean reversion strategy using VWAP as dynamic support/resistance. Excellent for ranging market conditions.",
    category: "Mean Reversion",
    winRate: 69.7,
    monthlyReturn: 6.9,
    riskRating: 2,
    maxDrawdown: 3.1,
    sharpeRatio: 2.7,
    totalTrades: 2100,
    isActive: true,
    isPremium: false,
    tags: ["VWAP", "Reversal", "Mean Reversion"],
  },
  {
    id: "strat-008",
    name: "Option Scalper",
    description: "Premium decay and momentum-based options scalping. Targets quick moves on weekly options with defined risk.",
    category: "Options",
    winRate: 67.5,
    monthlyReturn: 18.5,
    riskRating: 5,
    maxDrawdown: 12.4,
    sharpeRatio: 1.4,
    totalTrades: 3200,
    isActive: false,
    isPremium: true,
    tags: ["Options", "Scalping", "Premium"],
  },
  {
    id: "strat-009",
    name: "ICT Silver Bullet",
    description: "Captures high-displacement market structure shift setups within ICT Silver Bullet time windows. Enters on Fair Value Gap (FVG) mitigation.",
    category: "Smart Money",
    winRate: 78.4,
    monthlyReturn: 15.2,
    riskRating: 4,
    maxDrawdown: 5.1,
    sharpeRatio: 2.4,
    totalTrades: 640,
    isActive: true,
    isPremium: true,
    tags: ["ICT", "Silver Bullet", "FVG"],
  },
  {
    id: "strat-010",
    name: "Order Block Mitigation",
    description: "Enters on mitigation of institutional order blocks (OB) confirmed by lower timeframe market structure shifts and volume displacement.",
    category: "Smart Money",
    winRate: 74.2,
    monthlyReturn: 11.8,
    riskRating: 3,
    maxDrawdown: 4.8,
    sharpeRatio: 2.1,
    totalTrades: 920,
    isActive: true,
    isPremium: false,
    tags: ["OB", "Mitigation", "SMC"],
  },
  {
    id: "strat-011",
    name: "Liquidity Run (BSL/SSL Sweep)",
    description: "Identifies Buy-Side Liquidity (BSL) and Sell-Side Liquidity (SSL) pools, waiting for sweeps of session or daily highs/lows before entering on displacement.",
    category: "Liquidity",
    winRate: 79.1,
    monthlyReturn: 16.5,
    riskRating: 4,
    maxDrawdown: 6.2,
    sharpeRatio: 2.6,
    totalTrades: 810,
    isActive: false,
    isPremium: true,
    tags: ["Liquidity", "BSL", "SSL", "Sweeps"],
  },
  {
    id: "strat-012",
    name: "Premium/Discount Mean Reversion",
    description: "Uses multi-timeframe Fibonacci retracements to map premium/discount zones, entering reversal positions from extreme values back to equilibrium price.",
    category: "Mean Reversion",
    winRate: 71.5,
    monthlyReturn: 9.4,
    riskRating: 2,
    maxDrawdown: 3.5,
    sharpeRatio: 2.3,
    totalTrades: 1100,
    isActive: true,
    isPremium: false,
    tags: ["Fibonacci", "Discount", "Equilibrium"],
  },
  {
    id: "strat-013",
    name: "Bollinger Band Rebound",
    description: "Mean reversion strategy trading the deviations outside the 2.0 standard deviation bands, validated by candle confirmation.",
    category: "Mean Reversion",
    winRate: 66.4,
    monthlyReturn: 7.2,
    riskRating: 2,
    maxDrawdown: 4.5,
    sharpeRatio: 1.9,
    totalTrades: 1400,
    isActive: false,
    isPremium: false,
    tags: ["Bollinger", "Bands", "Reversion"],
  },
  {
    id: "strat-014",
    name: "Supertrend Alpha Crossover",
    description: "Dynamic trend following utilizing a dual Supertrend setup (10,3 and 7,1.5) to capture explosive impulses.",
    category: "Trend Following",
    winRate: 70.8,
    monthlyReturn: 13.5,
    riskRating: 3,
    maxDrawdown: 5.9,
    sharpeRatio: 2.2,
    totalTrades: 1150,
    isActive: false,
    isPremium: false,
    tags: ["Supertrend", "Trend", "Crossover"],
  },
  {
    id: "strat-015",
    name: "Heikin Ashi Momentum Ride",
    description: "Filters noise using Heikin Ashi candles to ride strong macro trend movements in stock futures.",
    category: "Momentum",
    winRate: 64.2,
    monthlyReturn: 10.1,
    riskRating: 3,
    maxDrawdown: 6.8,
    sharpeRatio: 1.7,
    totalTrades: 980,
    isActive: false,
    isPremium: false,
    tags: ["HeikinAshi", "Momentum", "NoiseFilter"],
  },
  {
    id: "strat-016",
    name: "Volume Spread Analysis",
    description: "Deciphers institutional accumulation and distribution phases using spread dynamics and volume bars.",
    category: "Volume",
    winRate: 73.1,
    monthlyReturn: 8.9,
    riskRating: 2,
    maxDrawdown: 3.4,
    sharpeRatio: 2.4,
    totalTrades: 890,
    isActive: false,
    isPremium: true,
    tags: ["VSA", "Accumulation", "Distribution"],
  },
  {
    id: "strat-017",
    name: "MACD Divergence Sniper",
    description: "Sniper entries on hidden and classic momentum divergences between MACD histogram and price actions.",
    category: "Momentum",
    winRate: 69.2,
    monthlyReturn: 9.3,
    riskRating: 3,
    maxDrawdown: 4.1,
    sharpeRatio: 2.0,
    totalTrades: 1250,
    isActive: false,
    isPremium: false,
    tags: ["MACD", "Divergence", "Sniper"],
  },
  {
    id: "strat-018",
    name: "Fibonacci Golden Pocket",
    description: "Trades the 61.8% to 65% 'Golden Pocket' retracement levels with high-probability order block confluence.",
    category: "Mean Reversion",
    winRate: 72.9,
    monthlyReturn: 11.5,
    riskRating: 3,
    maxDrawdown: 4.9,
    sharpeRatio: 2.3,
    totalTrades: 1040,
    isActive: false,
    isPremium: false,
    tags: ["Fibonacci", "GoldenPocket", "Pullback"],
  },
  {
    id: "strat-019",
    name: "Inside Bar Breakout",
    description: "Classic range volatility contraction breakout strategy trading the mother-baby bar patterns on daily charts.",
    category: "Breakout",
    winRate: 65.5,
    monthlyReturn: 8.7,
    riskRating: 2,
    maxDrawdown: 5.2,
    sharpeRatio: 1.6,
    totalTrades: 1600,
    isActive: false,
    isPremium: false,
    tags: ["InsideBar", "Breakout", "Volatility"],
  },
  {
    id: "strat-020",
    name: "Iron Condor Delta-Neutral",
    description: "Collects high-probability premium decay on indices by building weekly delta-neutral multi-leg spreads.",
    category: "Options",
    winRate: 82.5,
    monthlyReturn: 5.4,
    riskRating: 2,
    maxDrawdown: 3.0,
    sharpeRatio: 2.9,
    totalTrades: 520,
    isActive: false,
    isPremium: true,
    tags: ["IronCondor", "Options", "DeltaNeutral"],
  },
  {
    id: "strat-021",
    name: "Weekly Straddle Arbitrage",
    description: "Buys/Sells weekly option straddles based on implied volatility deviations relative to historical volatility ranges.",
    category: "Options",
    winRate: 75.3,
    monthlyReturn: 14.2,
    riskRating: 4,
    maxDrawdown: 8.9,
    sharpeRatio: 1.8,
    totalTrades: 780,
    isActive: false,
    isPremium: true,
    tags: ["Straddle", "Arbitrage", "Volatility"],
  },
  {
    id: "strat-022",
    name: "CPR Pivot Bounce",
    description: "Intraday mean reversion from Central Pivot Range levels, trading bounces from daily pivot points.",
    category: "Mean Reversion",
    winRate: 68.9,
    monthlyReturn: 7.8,
    riskRating: 2,
    maxDrawdown: 3.9,
    sharpeRatio: 2.1,
    totalTrades: 1350,
    isActive: false,
    isPremium: false,
    tags: ["CPR", "Pivots", "Intraday"],
  },
  {
    id: "strat-023",
    name: "Dynamic Trailing Follower",
    description: "Captures extended macro swings using ATR-based dynamic trailing stop lines for optimized capital harvesting.",
    category: "Trend Following",
    winRate: 62.1,
    monthlyReturn: 15.4,
    riskRating: 3,
    maxDrawdown: 7.2,
    sharpeRatio: 1.9,
    totalTrades: 690,
    isActive: false,
    isPremium: false,
    tags: ["ATR", "TrailingStop", "Trend"],
  },
  {
    id: "strat-024",
    name: "High-Frequency Arbitrage",
    description: "Exploits short-lived micro-second pricing gaps between spot index and options premiums.",
    category: "Scalping",
    winRate: 88.4,
    monthlyReturn: 6.2,
    riskRating: 1,
    maxDrawdown: 1.5,
    sharpeRatio: 3.8,
    totalTrades: 15400,
    isActive: false,
    isPremium: true,
    tags: ["HFT", "Arbitrage", "Microseconds"],
  },
  {
    id: "strat-025",
    name: "HNI Multi-Asset Index Basket",
    description: "Exclusively for HNIs. Institutional-grade dynamic basket allocating capital across indices, gold ETFs, and treasury contracts to hedge systemic risks.",
    category: "HNI Exclusive",
    winRate: 84.2,
    monthlyReturn: 3.9,
    riskRating: 1,
    maxDrawdown: 2.1,
    sharpeRatio: 3.4,
    totalTrades: 210,
    isActive: false,
    isPremium: true,
    isHniOnly: true,
    minInvestment: 5000000,
    tags: ["HNI", "MultiAsset", "Hedging", "SafeGrowth"],
  },
  {
    id: "strat-026",
    name: "Delta Hedging Options Engine",
    description: "Exclusively for HNIs. Dynamically adjusts hedge ratios using computerized algorithms to maintain neutral portfolio delta across major options expires.",
    category: "Options",
    winRate: 87.5,
    monthlyReturn: 8.2,
    riskRating: 2,
    maxDrawdown: 3.5,
    sharpeRatio: 3.1,
    totalTrades: 1180,
    isActive: false,
    isPremium: true,
    isHniOnly: true,
    minInvestment: 7500000,
    tags: ["HNI", "DeltaHedging", "Algorithmic", "Spread"],
  },
  {
    id: "strat-027",
    name: "Smart Money Mega-Sized Sweeps",
    description: "Exclusively for HNIs. Identifies block-trades and sweeps executed by mutual funds and FIIs, shadowing large size movements in option chains.",
    category: "Smart Money",
    winRate: 79.8,
    monthlyReturn: 16.4,
    riskRating: 4,
    maxDrawdown: 6.9,
    sharpeRatio: 2.5,
    totalTrades: 480,
    isActive: false,
    isPremium: true,
    isHniOnly: true,
    minInvestment: 10000000,
    tags: ["HNI", "BlockTrades", "FIIFlow", "HighSize"],
  },
  {
    id: "strat-028",
    name: "Algorithmic Equity Momentum Lab",
    description: "Exclusively for HNIs. High-volume momentum portfolio scanning across top-100 midcap stocks with custom allocation parameters for maximizing alpha.",
    category: "Momentum",
    winRate: 74.5,
    monthlyReturn: 19.8,
    riskRating: 4,
    maxDrawdown: 9.2,
    sharpeRatio: 2.2,
    totalTrades: 620,
    isActive: false,
    isPremium: true,
    isHniOnly: true,
    minInvestment: 5000000,
    tags: ["HNI", "Midcaps", "Alpha", "Momentum"],
  },
  {
    id: "strat-029",
    name: "Cross-Broker Volatility Arbitrage",
    description: "Exclusively for HNIs. Executes algorithmic arbitrage setups capitalizing on temporary volatility imbalances between multiple NSE broker feeds.",
    category: "HNI Exclusive",
    winRate: 91.2,
    monthlyReturn: 6.8,
    riskRating: 1,
    maxDrawdown: 1.2,
    sharpeRatio: 4.2,
    totalTrades: 3450,
    isActive: false,
    isPremium: true,
    isHniOnly: true,
    minInvestment: 12000000,
    tags: ["HNI", "Arbitrage", "LowRisk", "Feeds"],
  },
  {
    id: "strat-030",
    name: "Institutional Index Arbitrage",
    description: "Exclusively for HNIs. Spot vs. Future vs. Option premium mathematical arbitrage with continuous real-time hedging triggers.",
    category: "HNI Exclusive",
    winRate: 93.4,
    monthlyReturn: 5.1,
    riskRating: 1,
    maxDrawdown: 0.8,
    sharpeRatio: 4.9,
    totalTrades: 5800,
    isActive: false,
    isPremium: true,
    isHniOnly: true,
    minInvestment: 8000000,
    tags: ["HNI", "Arbitrage", "Index", "Riskless"],
  },
];

// ============================================================
// Trade Journal
// ============================================================

export const tradeEntries: TradeEntry[] = historicalTrades;

// ============================================================
// Equity Curve & Monthly Returns
// ============================================================

function generateEquityCurve(): EquityPoint[] {
  const data: EquityPoint[] = [];
  let equity = 1000000;
  let peak = equity;
  const startDate = new Date("2024-06-01");

  for (let i = 0; i < 252; i++) {
    const date = new Date(startDate);
    date.setDate(date.getDate() + i);
    const dailyReturn = (Math.random() - 0.42) * 0.015;
    equity = equity * (1 + dailyReturn);
    peak = Math.max(peak, equity);
    const drawdown = ((peak - equity) / peak) * 100;

    data.push({
      date: date.toISOString().split("T")[0],
      equity: Math.round(equity),
      drawdown: Math.round(drawdown * 100) / 100,
    });
  }
  return data;
}

export const equityCurveData: EquityPoint[] = generateEquityCurve();

export const monthlyReturnsData: MonthlyReturn[] = [
  { month: "Jan", year: 2025, returnPercent: 5.2, trades: 42 },
  { month: "Feb", year: 2025, returnPercent: -2.1, trades: 38 },
  { month: "Mar", year: 2025, returnPercent: 8.7, trades: 51 },
  { month: "Apr", year: 2025, returnPercent: 3.4, trades: 45 },
  { month: "May", year: 2025, returnPercent: 11.2, trades: 58 },
  { month: "Jun", year: 2025, returnPercent: 6.8, trades: 47 },
  { month: "Jul", year: 2024, returnPercent: -1.3, trades: 39 },
  { month: "Aug", year: 2024, returnPercent: 7.5, trades: 44 },
  { month: "Sep", year: 2024, returnPercent: 4.1, trades: 41 },
  { month: "Oct", year: 2024, returnPercent: 9.8, trades: 53 },
  { month: "Nov", year: 2024, returnPercent: -3.2, trades: 36 },
  { month: "Dec", year: 2024, returnPercent: 6.4, trades: 48 },
];

// ============================================================
// Backtest Results (Pre-generated)
// ============================================================

export const backtestResult: BacktestResult = {
  totalTrades: 186,
  winningTrades: 136,
  losingTrades: 50,
  winRate: 73.1,
  profitFactor: 2.84,
  maxDrawdown: 42500,
  maxDrawdownPercent: 4.25,
  netProfit: 287400,
  netProfitPercent: 28.74,
  sharpeRatio: 2.31,
  avgWin: 3250,
  avgLoss: 1800,
  largestWin: 18500,
  largestLoss: 8200,
  equityCurve: equityCurveData,
  monthlyReturns: monthlyReturnsData,
  trades: tradeEntries.map((t) => ({
    id: t.id,
    entryDate: t.date,
    exitDate: t.date,
    direction: t.direction,
    entryPrice: t.entryPrice,
    exitPrice: t.exitPrice,
    pnl: t.pnl,
    pnlPercent: t.pnlPercent,
    holdingPeriod: t.duration,
  })),
};

// ============================================================
// Broker Configs
// ============================================================

export const brokerConfigs: BrokerConfig[] = [
  { id: "b-001", name: "Dhan", logo: "🟢", status: "connected", capitalAllocated: 500000, riskPerTrade: 1.5, maxDailyLoss: 15000, autoTradingEnabled: true, todayPnl: 12500, tradesExecuted: 8 },
  { id: "b-002", name: "Zerodha", logo: "🔵", status: "disconnected", capitalAllocated: 1000000, riskPerTrade: 1.0, maxDailyLoss: 25000, autoTradingEnabled: false, todayPnl: 0, tradesExecuted: 0 },
  { id: "b-003", name: "Angel One", logo: "🟠", status: "connected", capitalAllocated: 750000, riskPerTrade: 2.0, maxDailyLoss: 20000, autoTradingEnabled: true, todayPnl: 8750, tradesExecuted: 5 },
  { id: "b-004", name: "Shoonya", logo: "🟣", status: "error", capitalAllocated: 250000, riskPerTrade: 1.5, maxDailyLoss: 10000, autoTradingEnabled: false, todayPnl: -2300, tradesExecuted: 3 },
  { id: "b-005", name: "Fyers", logo: "🔴", status: "connected", capitalAllocated: 300000, riskPerTrade: 1.2, maxDailyLoss: 8000, autoTradingEnabled: true, todayPnl: 4300, tradesExecuted: 2 },
  { id: "b-006", name: "Upstox", logo: "🟡", status: "disconnected", capitalAllocated: 600000, riskPerTrade: 1.5, maxDailyLoss: 12000, autoTradingEnabled: false, todayPnl: 0, tradesExecuted: 0 },
  { id: "b-007", name: "Groww", logo: "🟢", status: "connected", capitalAllocated: 400000, riskPerTrade: 1.0, maxDailyLoss: 10000, autoTradingEnabled: true, todayPnl: 6500, tradesExecuted: 4 },
  { id: "b-008", name: "Kotak Securities", logo: "🔴", status: "disconnected", capitalAllocated: 800000, riskPerTrade: 1.5, maxDailyLoss: 16000, autoTradingEnabled: false, todayPnl: 0, tradesExecuted: 0 },
  { id: "b-009", name: "5paisa", logo: "🔵", status: "connected", capitalAllocated: 200000, riskPerTrade: 1.8, maxDailyLoss: 7500, autoTradingEnabled: true, todayPnl: 3100, tradesExecuted: 2 },
  { id: "b-010", name: "IIFL Securities", logo: "🟠", status: "error", capitalAllocated: 500000, riskPerTrade: 1.5, maxDailyLoss: 15000, autoTradingEnabled: false, todayPnl: -1200, tradesExecuted: 1 },
  { id: "b-011", name: "Motilal Oswal", logo: "🟡", status: "connected", capitalAllocated: 1200000, riskPerTrade: 1.0, maxDailyLoss: 24000, autoTradingEnabled: true, todayPnl: 14200, tradesExecuted: 6 },
  { id: "b-012", name: "ICICI Direct", logo: "🟠", status: "disconnected", capitalAllocated: 1500000, riskPerTrade: 0.8, maxDailyLoss: 30000, autoTradingEnabled: false, todayPnl: 0, tradesExecuted: 0 },
  { id: "b-013", name: "HDFC Securities", logo: "🔵", status: "connected", capitalAllocated: 1000000, riskPerTrade: 1.0, maxDailyLoss: 20000, autoTradingEnabled: true, todayPnl: 8900, tradesExecuted: 3 },
  { id: "b-014", name: "Sharekhan", logo: "🟢", status: "disconnected", capitalAllocated: 450000, riskPerTrade: 1.5, maxDailyLoss: 9000, autoTradingEnabled: false, todayPnl: 0, tradesExecuted: 0 },
  { id: "b-015", name: "Alice Blue", logo: "🔵", status: "connected", capitalAllocated: 350000, riskPerTrade: 1.5, maxDailyLoss: 10000, autoTradingEnabled: true, todayPnl: -500, tradesExecuted: 1 },
];

// ============================================================
// Market Intelligence
// ============================================================

export const marketSentiment: MarketSentiment = {
  overall: 65,
  label: "Greed",
  bullishProbability: 72,
  bearishProbability: 28,
};

export const sectorStrengthData: SectorStrength[] = [
  { name: "Banking", strength: 78, change: 2.1, volume: "₹8,450Cr" },
  { name: "IT", strength: -35, change: -1.2, volume: "₹5,200Cr" },
  { name: "Auto", strength: 65, change: 1.8, volume: "₹3,800Cr" },
  { name: "Pharma", strength: 12, change: 0.3, volume: "₹2,100Cr" },
  { name: "Energy", strength: 52, change: 1.5, volume: "₹6,700Cr" },
  { name: "FMCG", strength: -18, change: -0.4, volume: "₹1,900Cr" },
  { name: "Metal", strength: 45, change: 1.1, volume: "₹4,300Cr" },
  { name: "Realty", strength: 82, change: 3.2, volume: "₹2,800Cr" },
  { name: "Capital Goods", strength: 38, change: 0.8, volume: "₹1,600Cr" },
  { name: "Telecom", strength: 25, change: 0.5, volume: "₹3,100Cr" },
];

export const smartMoneyActivity: SmartMoneyActivity[] = [
  { id: "sm-001", time: "14:32", type: "accumulation", symbol: "SBIN", value: 125000000, description: "Large institutional buy detected — ₹12.5Cr block at 840-845 range" },
  { id: "sm-002", time: "13:45", type: "distribution", symbol: "HDFCBANK", value: 89000000, description: "FII selling pressure — ₹8.9Cr distributed in 15min window" },
  { id: "sm-003", time: "12:15", type: "block_deal", symbol: "RELIANCE", value: 250000000, description: "Block deal — ₹25Cr traded at ₹2,942 between institutions" },
  { id: "sm-004", time: "11:30", type: "accumulation", symbol: "TATAMOTORS", value: 67000000, description: "DII accumulation — ₹6.7Cr systematic buying in auto sector" },
  { id: "sm-005", time: "10:45", type: "bulk_deal", symbol: "BAJFINANCE", value: 180000000, description: "Bulk deal — ₹18Cr traded by foreign portfolio investor" },
  { id: "sm-006", time: "10:15", type: "accumulation", symbol: "INFY", value: 45000000, description: "Mutual fund buying — ₹4.5Cr accumulated at support zone" },
];

export const volatilityData: VolatilityData = {
  indiaVix: 13.45,
  vixChange: -5.2,
  vixTrend: "falling",
  historicalAvg: 15.8,
};

// ============================================================
// Analytics
// ============================================================

export const strategyPerformanceData: StrategyPerformance[] = [
  { name: "EMA 9/15 Scalper", winRate: 72.4, totalReturn: 45200, trades: 156, avgPnl: 289.7, profitFactor: 2.1 },
  { name: "VWAP Reversal", winRate: 69.7, totalReturn: 38700, trades: 128, avgPnl: 302.3, profitFactor: 2.7 },
  { name: "ORB", winRate: 68.2, totalReturn: 52100, trades: 142, avgPnl: 366.9, profitFactor: 1.6 },
  { name: "Momentum Hunter", winRate: 71.1, totalReturn: 61400, trades: 98, avgPnl: 626.5, profitFactor: 2.3 },
  { name: "Smart Money", winRate: 76.3, totalReturn: 72800, trades: 72, avgPnl: 1011.1, profitFactor: 1.9 },
];

// ============================================================
// Telegram Config
// ============================================================

export const telegramConfig: TelegramConfig = {
  botToken: "",
  chatId: "",
  isConnected: false,
  autoSendEnabled: false,
  signalTemplate: `🚀 *Trade Metrix AI Signal*

📊 {symbol} — *{direction}*

▶️ Entry: {entry}
🛑 Stop Loss: {stopLoss}
🎯 Target: {target}

📈 Confidence: {confidence}%
💡 Reasoning: {reasoning}

⏰ Generated: {time}
🤖 Powered by Trade Metrix AI`,
  messagesSentToday: 0,
};

// ============================================================
// Settings
// ============================================================

export const defaultSettings: UserSettings = {
  theme: "dark",
  notifications: {
    signalAlerts: true,
    tradeExecuted: true,
    dailySummary: true,
    riskAlerts: true,
    emailNotifications: false,
    pushNotifications: true,
  },
  risk: {
    maxPositionSize: 100000,
    maxDailyLoss: 25000,
    maxOpenPositions: 5,
    riskPerTrade: 1.5,
    emergencyStopEnabled: true,
    trailingStopEnabled: false,
  },
  apiKeys: {},
  profile: {
    name: "Trader Pro",
    email: "trader@trademetrix.ai",
    plan: "pro",
  },
};
